version: 2.1

executors:
  renovate:
    docker:
      - image: renovate/renovate:latest
jobs:
  run-renovate:
    executor: renovate
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  renovate-workflow:
    jobs:
      - run-renovate
