version: 2.1

executors:
  renovate:
    docker:
      - image: renovate/renovate:latest
jobs:
  run-renovate:
    executor: renovate
    steps:
      - checkout
      - run:
          name: "run renovate"
          command: "renovate"
          environment:
            RENOVATE_CONFIG_FILE: ./renovate-config.js
            LOG_LEVEL: "info"
            LOG_FORMAT: "json"

workflows:
  renovate-workflow:
    jobs:
      - run-renovate
